%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Original Matlab version used to write the code: R2014b
%
%FOR ANY QUESTION RELATED TO THE MATLAB FILES, PLEASE CONTACT JOHANNES
%OVERVELDE AT J.T.B.OVERVELDE@GMAIL.COM (WWW.OVERVELDE.COM)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear, close all, clc, format long

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%CHOOSE PREDEFINED GEOMETRY, SIMULATION AND PLOT OPTIONS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SimCase=1

switch SimCase
    case 1
        opt=initOpt('inputType','individual',...
                    'template','truncated tetrahedron',...
                    'plot','result',...
                    'interval', 10,'saveFig','on','periodic','on','figDPI',300,...
                    'saveMovie', 'on', 'safeMovieAntiAlias', 0,...
                    'relAlgor', 'sqp', 'gradDescStep', 1e-1, 'gradDescTol', 1e-9,...
                    'constrFace','off','constrEdge','off',...
                    'Khinge',0.0005,'Kedge',1,'Kface',1,'KtargetAngle',1,...
                    'relInterval', 10, 'constAnglePerc',0.989);
        opt.angleConstrFinal(1).val=[3  -pi*0.985
%                                      2 -pi*0.985
                                     41 -pi*0.985
                                     ];
%         opt.angleConstrFinal(2).val=[3  -1.230959417
%                                      18 -1.230959417];
%         opt.angleConstrFinal(3).val=[3  -pi*0.99
%                                      18  -pi*0.99];
%         opt.angleConstrFinal(4).val=[3  -1.230959417
%                                      18 -1.230959417];
%         opt.angleConstrFinal(3).val=[1 -pi*0.985
%                                      2 -pi*0.985
%                                      19 -pi*0.985];
        opt.angleConstrFinal(2).val=[];
    case 2
        opt=initOpt('inputType','individual',...
                    'template','cuboctahedron',...
                    'plot','result',...
                    'interval',1,'saveFig','off','periodic','off',...
                    'constrFace','off','constrEdge','off',...
                    'Khinge',0.001,'Kedge',1,'Kface',1,'KtargetAngle',1,...
                    'constAnglePerc',0.98);
        opt.angleConstrFinal(1).val=[16 -pi*0.975
                                     18 -pi*0.975
                                     30 -pi*0.975
                                     53 -pi*0.975];        
    case 3        
        opt=initOpt('inputType','preDefined',...
                    'template','#22',...
                    'plot','result',...
                    'interval',20,'saveFig','off','periodic','on',...
                    'constrFace','on','constrEdge','on',...
                    'Khinge',0.001,'Kedge',1,'Kface',1,'KtargetAngle',1,...
                    'constAnglePerc',0.98); 
        opt.angleConstrFinal(1).val=[1  -pi*0.975];
        opt.angleConstrFinal(2).val=[1  -pi*0.975
                                     13 -pi*0.975];
    case 4
        opt=initOpt('inputType','preDefined',...
                    'template','#26',...
                    'plot','result',...
                    'interval',20,'saveFig','off','periodic','on',...
                    'constrFace','on','constrEdge','on',...
                    'Khinge',0.001,'Kedge',1,'Kface',1,'KtargetAngle',1,...
                    'constAnglePerc',0.98);  
        opt.angleConstrFinal(1).val=[1  -pi*0.975];
    case 5
        opt=initOpt('inputType','individual',...
                    'template','rhombicuboctahedron',...
                    'plot','result',...
                    'interval',5,'saveFig','off','periodic','off',...
                    'constrFace','on','constrEdge','off',...
                    'Khinge',0.001,'Kedge',1,'Kface',1,'KtargetAngle',1,...
                    'constAnglePerc',0.99);
        opt.angleConstrFinal(1).val=[111 -pi*0.985
                                     105 -pi*0.985
                                     116 -pi*0.985
                                     106 -pi*0.985];
        opt.angleConstrFinal(2).val=[131 -pi*0.985
                                     125 -pi*0.985
                                     126 -pi*0.985
                                     136 -pi*0.985];
        opt.angleConstrFinal(3).val=[];
    case 6
        opt=initOpt('inputType','preDefined',...
                    'template','#18',...
                    'plot','result',...
                    'interval',10,'saveFig','off','periodic','on',...
                    'constrFace','on','constrEdge','on',...
                    'Khinge',0.001,'Kedge',1,'Kface',1,'KtargetAngle',1,...
                    'constAnglePerc',0.98);  
        opt.angleConstrFinal(1).val=[1  -pi*0.975];
    case 7
        opt=initOpt('inputType','user',...
                    'template','userInputFile1',...
                    'plot','result',...
                    'interval',1,'saveFig','off','periodic','on',...
                    'constrFace','on','constrEdge','off',...
                    'Khinge',0.001,'Kedge',1,'Kface',1,'KtargetAngle',1,...
                    'constAnglePerc',0.98);  
        opt.angleConstrFinal(1).val=[19  -pi*0.6
                                     47  -pi*0.6]; 
        opt.angleConstrFinal(2).val=[];
end

%SOLVER OPTIONS
opt.options=optimoptions('fmincon','GradConstr','on','GradObj','on',...
                         'tolfun',1e-5','tolx',1e-9,'tolcon',1e-5,...
                         'Display','off','DerivativeCheck','off','maxfunevals',100000);
%                          'FiniteDifferenceType', 'central', 'FiniteDifferenceStepSize', eps^(1));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%BUILD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[unitCell,extrudedUnitCell,opt]=buildGeometry(opt);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%ANALYSIS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[result,extrudedUnitCell]=findDeformation(unitCell,extrudedUnitCell,opt);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%OUTPUT AND PLOT GEOMETRY
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
outputResults(unitCell,extrudedUnitCell,result,opt)

